// Mocks generated by Mockito 5.4.4 from annotations
// in shopping_app/test/dashboard/tap/cart/data/cart_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;
import 'package:shopping_app/src/dashboard/tab/cart/data/model/product_request.dart'
    as _i5;
import 'package:shopping_app/src/dashboard/tab/cart/data/remote/cart_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CartService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartService extends _i1.Mock implements _i3.CartService {
  MockCartService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<void>> checkOut(_i5.ProductRequest? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkOut,
          [model],
        ),
        returnValue:
            _i4.Future<_i2.HttpResponse<void>>.value(_FakeHttpResponse_0<void>(
          this,
          Invocation.method(
            #checkOut,
            [model],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<void>>);
}
