// Mocks generated by Mockito 5.4.4 from annotations
// in shopping_app/test/dashboard/tap/shopping/data/shopping_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;
import 'package:shopping_app/src/dashboard/tab/shopping/data/model/item_response.dart'
    as _i6;
import 'package:shopping_app/src/dashboard/tab/shopping/data/model/product_response.dart'
    as _i5;
import 'package:shopping_app/src/dashboard/tab/shopping/data/remote/shopping_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ShoppingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShoppingService extends _i1.Mock implements _i3.ShoppingService {
  MockShoppingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpResponse<_i5.ProductResponse?>> getProduct(
    int? limit,
    String? cursor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [
            limit,
            cursor,
          ],
        ),
        returnValue: _i4.Future<_i2.HttpResponse<_i5.ProductResponse?>>.value(
            _FakeHttpResponse_0<_i5.ProductResponse?>(
          this,
          Invocation.method(
            #getProduct,
            [
              limit,
              cursor,
            ],
          ),
        )),
      ) as _i4.Future<_i2.HttpResponse<_i5.ProductResponse?>>);

  @override
  _i4.Future<_i2.HttpResponse<List<_i6.ItemResponse>?>>
      getRecommendedProduct() => (super.noSuchMethod(
            Invocation.method(
              #getRecommendedProduct,
              [],
            ),
            returnValue:
                _i4.Future<_i2.HttpResponse<List<_i6.ItemResponse>?>>.value(
                    _FakeHttpResponse_0<List<_i6.ItemResponse>?>(
              this,
              Invocation.method(
                #getRecommendedProduct,
                [],
              ),
            )),
          ) as _i4.Future<_i2.HttpResponse<List<_i6.ItemResponse>?>>);
}
